### PR TITLE
Get controller tests into rails5 format

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

A PR into someone else's fork of your own thing has got to be on the oss scavenger hunt somewhere. 

This brings our controller tests up to speed with the rails 5 format.

All working except for one thing in the users controller test. I think. I'll push the rest of this over later this week.

### CODE REVIEW

**Comment by colinxfleming** [comment]
ps be advised -- this has some cruft from master in it, my junk is 	85e275e and after. Happy to rebase if necessary.

**Comment by colinxfleming** [comment]
cc @lomky

**Comment by DarthHater** [comment]
@colinxfleming if you could rebase that would be great /lumberg voice. Let's keep the commit history clean (since this is a large change and it would be nice to have the noise limited to what we did).

**Comment by colinxfleming** [comment]
On it. Here goes nothing

**Pull request closed without merging**
